### ISSUE TITLE
Kanban board for assignment of tasks - Venon Precision Project

### ISSUE THREAD

**Issue by chelobotix** [limavfabio/VenomPrecision-back-end#12]
This issue is related to the Kanban board for the Final Capstone Project:
 [Frontend Repo](https://github.com/limavfabio/VenomPrecision-back-end)
 [Backend Repo](https://github.com/limavfabio/VenomPrecision-front-end)

There are four members in our group: @limavfabio, @anderCM, @JakariaJishan and @chelobotix .

Link to the Kanban board: https://github.com/users/limavfabio/projects/2
![image](https://github.com/limavfabio/VenomPrecision-back-end/assets/65084923/ada6c4c1-d819-40bf-836b-90cde93da03f)

**Comment by Meltrust** [comment]
Hi @chelobotix,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  
Congratulations! 🎉 

### To highlight

- All cards have descriptions, pointings, and have been assigned.  Pointings are fairly equal. ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
